# Generated by Django 5.1.7 on 2025-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('education_name', models.CharField(max_length=255)),
                ('olymp_name', models.CharField(max_length=255)),
                ('orin', models.CharField(choices=[('orin1', "1-o'rin"), ('orin2', "2-o'rin"), ('orin3', "3-o'rin")], max_length=10)),
            ],
        ),
    ]
