# Generated by Django 5.1.7 on 2025-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education_name',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(upload_to='generated/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orin',
            field=models.IntegerField(choices=[(1, '1-o‘rin'), (2, '2-o‘rin'), (3, '3-o‘rin'), (4, 'Tashakkurnoma')]),
        ),
    ]
