# Generated by Django 5.1.7 on 2025-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_user_education_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='generated/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orin',
            field=models.CharField(choices=[('1', '1-o‘rin'), ('2', '2-o‘rin'), ('3', '3-o‘rin')], max_length=1),
        ),
    ]
