# Generated by Django 5.1.7 on 2025-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_file_path_alter_user_orin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
