# Generated by Django 5.1.7 on 2025-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_delete_user_alter_certificate_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('otm_name', models.CharField(max_length=255)),
                ('orin', models.PositiveIntegerField(choices=[(1, "1-o'rin"), (2, "2-o'rin"), (3, "3-o'rin")])),
                ('musobaqa_nomi', models.CharField(max_length=255)),
            ],
        ),
    ]
