# Generated by Django 5.1.7 on 2025-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
