# Generated by Django 5.1.7 on 2025-03-25 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_delete_certificate_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fan',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
