# Generated by Django 5.1.7 on 2025-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_user_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orin',
            field=models.PositiveIntegerField(blank=True, choices=[(1, "1-o'rin"), (2, "2-o'rin"), (3, "3-o'rin")], null=True),
        ),
    ]
