# Generated by Django 5.1.7 on 2025-03-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_user_orin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pdf_file', models.FileField(upload_to='certificates/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='certificates/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
