# Generated by Django 5.1.7 on 2025-04-01 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
