# Generated by Django 5.1.7 on 2025-04-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_alter_user_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
