# Generated by Django 5.1.7 on 2025-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_alter_user_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='musobaqa_nomi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
