# Generated by Django 4.2.20 on 2025-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_alter_user_musobaqa_nomi_alter_user_otm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fan', models.CharField(max_length=255)),
                ('otm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('orin', models.PositiveIntegerField(blank=True, choices=[(1, "1-o'rin"), (2, "2-o'rin"), (3, "3-o'rin")], null=True)),
                ('musobaqa_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('diplom_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
