# Generated by Django 4.2.20 on 2025-04-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_diplomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomuser',
            name='orin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
