# Generated by Django 4.2.20 on 2025-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_alter_diplomuser_orin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomuser',
            name='diplom_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
